### ISSUE TITLE
Key mapping for <C-Space> (toggle todo task complete) is mapped in select mode and not normal or visual mode

### ISSUE THREAD

**Issue by acepukas** [vimwiki/vimwiki#1416]
## Issue Requirements

- [X] Include the VimWiki settings from your `.vimrc`
- [X] Include the syntax you are using (default / Markdown / MediaWiki) 
- [X] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [X] Include the output of `:VimwikiShowVersion`.

## VimWiki Settings

```vimscript
let g:vimwiki_list = [{
  \ 'automatic_nested_syntaxes': 1,
  \ 'auto_export': 1,
  \ 'path_html': '/var/www/my.vimwiki.net',
  \ 'path': '~/vimwiki/',
  \ 'syntax': 'markdown',
  \ 'ext': '.md',
  \ 'links_space_char': '-',
  \ 'css_name': 'style.css',
  \ 'template_path': '~/vimwiki/templates',
  \ 'template_default': 'default',
  \ 'template_ext': '.tmpl',
  \ 'custom_wiki2html': 'vw2html',
  \ 'custom_wiki2html_args': '-chroma-tab-width=2 -chroma-with-classes=t',
  \ }]

let g:vimwiki_global_ext = 0
let g:vimwiki_toc_header_level = 2
let g:vimwiki_toc_link_format = 1
```

## Syntax Type

`Markdown`

## Description of Issue

The `<C-Space>` mapping is only active in "select" mode. Output from command `:map <C-Space>`:

`s  <C-Space>    @<Plug>VimwikiToggleListItem`

If you have your cursor on a todo item line and, in normal mode, type `gh` to enter select mode and the <C-Space> command will properly toggle the item then, but only then.

Attempting to use the key map with `:execute` via `:execute "normal \<C-Space>"` has no effect.

In a similar issue someone else had with the same mapping, it turned out they had a key mapping for their Gnome desktop environment that was interfering with the VimWiki mapping. I'm using Gnome as well but I checked my key mappings and on my system the mapping is `Super+Space` and I don't have anything mapped to `Ctrl+Space`.

I'm using VimWiki with `neovim`. Maybe a compatibility issue?

## VimWiki Version Given By `:VimwikiShowVersion`

`2024.01.24`

**Comment by acepukas** [comment]
In the issue description I mentioned that I tested the mapping on a todo item line. That was in a vimwiki file.

I uninstalled the vimwiki plugin and reinstalled but the issue persists.

**Comment by Sage1918** [comment]
Hmm... This is very strange. 

Could you try `:VimwikiToggleListItem` while the cursor is on a list entry and tell the result?

**Comment by acepukas** [comment]
Yes, `:VimwikiToggleListItem` works as intended when the cursor is on a todo item line in a vimwiki file. Seems it's just the mapping that is affected.

**Comment by Sage1918** [comment]
You can add this to your neovim config as a temporary fix:
`nmap <C-Space> <cmd>VimwikiToggleListItem<CR>`  or 
`vim.keymap.set('n', '<C-Space>', '<cmd>VimwikiToggleListItem<CR>')`

Which version of neovim are you using?

**Comment by acepukas** [comment]
Setting the key mapping explicitly works. Suppose I should have tried that before hand.

I using neovim version `v0.10.0`.

**Comment by acepukas** [comment]
Well, this is embarrassing but the problem was a conflict with another plugin. It turns out `nvim-treesitter` had a feature activated in my config that used to `<C-Space>` to incrementally select larger and larger scopes. When I deactivated that vimwiki's `<C-Space>` started working fine. What threw me off is when in a vimwiki file and using `:map <C-Space>` only the mapping for vimwiki was shown and not any other mappings for `<C-Space>`. Outside of a vimwiki file, I could see the other mappings. Sorry for the goose chase.
