### ISSUE TITLE
:VimwikiCheckLinks not tracking Markdown style links.

### ISSUE THREAD

**Issue by hackabletype** [vimwiki/vimwiki#829]
Prior to submitting a new issue make sure to complete these steps:

- [x] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.

~I'm not a vim script developer. I wanna help, so here's a bug report. On cursory glance, it doesn't look like `dev` has this issue fixed.~

Edit: figured out how to install the dev branch using VimPlug, and this issue seems to be corrected.

- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`

Using NeoVim v0.4.3

`init.vim` (relevant lines):
```
" vimwiki prereqs
set nocompatible
filetype plugin on
syntax on

" vimwiki stuff
Plug 'vimwiki/vimwiki'

" vim-zettel
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'michal-h21/vim-zettel'
Plug 'https://github.com/alok/notational-fzf-vim'

" # Vimwiki

:let mapleader=","
let g:vimwiki_list = [
    \{'path': '/Data/Repos/wiki/', 'syntax': 'markdown', 'ext': '.md'}
  \]

" ## vim-zettel

" Filename format. The filename is created using strftime() function
let g:zettel_format = "%Y%m%d-%H%M"

" command used for VimwikiSearch 
" possible values: "ag", "rg", "grep"
let g:zettel_fzf_command = "ag"

" ## Notational FZF
let g:nv_search_paths = ['/Data/Repos/wiki']
```

- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.

`:VimwikiCheckLinks` not reporting correctly when markdown style links are being used.

files  listing:
```
➜ ls
20200310-1211.md      README.md             index.md              zettelkasten-inbox.md
20200310-1216.md      contents.md           tags.md
```

With an index.md as follows:
```
# wiki

[[contents]]
[[tags]]

## Zettelkasten

[[zettelkasten-inbox]]
```

`:VimwikiCheckLinks` generates:
```
/Data/Repos/wiki/index.md                                                                 1,0-1          All
  1 || /Data/Repos/wiki/20200310-1211.md is not reachable from the index file
  2 || /Data/Repos/wiki/20200310-1216.md is not reachable from the index file
  3 || /Data/Repos/wiki/README.md is not reachable from the index file
~
~
[Quickfix List] :setqflist()                                                                         1,1             All
```

However, if we use Markdown style links in an index.md as follows:
```
# wiki

[contents](contents)
[tags](tags)

## Zettelkasten

[zettelkasten inbox](zettelkasten-inbox)
```

`:VimwikiCheckLinks` generates:
```
/Data/Repos/wiki/index.md                                                                 10,0-1         Bot
  1 || /Data/Repos/wiki/20200310-1211.md is not reachable from the index file
  2 || /Data/Repos/wiki/20200310-1216.md is not reachable from the index file
  3 || /Data/Repos/wiki/README.md is not reachable from the index file
  4 || /Data/Repos/wiki/contents.md is not reachable from the index file
  5 || /Data/Repos/wiki/tags.md is not reachable from the index file
  6 || /Data/Repos/wiki/zettelkasten-inbox.md is not reachable from the index file
~
~
[Quickfix List] :setqflist()                                                                         1,1             All
```

This issue may relate to @lucasdf's PR [comment](https://github.com/vimwiki/vimwiki/pull/816#issuecomment-581087397) regarding markdown link support.

This may also relate to [issue 611](https://github.com/vimwiki/vimwiki/issues/611) and [issue 610](https://github.com/vimwiki/vimwiki/issues/610)

- [x] Include the output of `:VimwikiShowVersion`.

Stable version: '2.4.1'

**Comment by hackabletype** [comment]
Sorry, after figuring out how to install the dev branch and testing with vimplug, it appears that this issue has been sorted.
