### ISSUE TITLE
Make all appropriate settings wikilocal

### ISSUE THREAD

**Issue by Nudin** [vimwiki/vimwiki#894]
For historic reason some settings are global even though there is no reason to have them not as wikilocal settings. Therefore, it isn't possible to have multiple wikis with different values for these settings.

These are settings that affect the wikitext and should therefore be changeable on a per-wiki scope:
- [x] vimwiki_listsyms
- [x] vimwiki_listsym_rejected
- [x] vimwiki_list_ignore_newline (5700313e882814)
- [x] vimwiki_text_ignore_newline
- [x] vimwiki_markdown_link_ext (4672deb44e34b8)
- [x] vimwiki_toc_header, vimwiki_toc_header_level, vimwiki_toc_link_format (c4570886b04)

These are options that only change the displaying, they could be wikilocal but for most users it's also fine if they are global only:

- [x] vimwiki_hl_headers
- [x] vimwiki_hl_cb_checked
- [x] vimwiki_folding
- [x] vimwiki_create_link

The following options only make sense as global options and should stay such:
- vimwiki_use_calendar
- vimwiki_menu
- vimwiki_ext2syntax
- vimwiki_global_ext

Related Issues:

- [X] Unify global and wiki-local user options #257  (Closed in favor of this one)
- [x] make `g:vimwiki_toc_header` a per-wiki option #127
- [x] Support for wikis without adding path to g:vimwiki_list #854
- [x] Pressing enter to create a [[double bracket]] #892
- [x] Allow setting default path_html for temporary wikis #250

**Comment by Nudin** [comment]
PR #889 makes the first two (`vimwiki_listsyms` & `vimwiki_listsym_rejected`) wiki-local. To do so it adds "tooling" to have settings that are usable as global and wiki-local. Through this vimwiki stays backward compatible: global settings continue to work but local options are used if pressent.

**Comment by tinmarino** [comment]
Hacktoberfest point for any issue referenced or referencing this one and some are pretty easy: just dictionary refactoring.

**Comment by tinmarino** [comment]
I think most of the refactoring have been done by now. If someone have specific variables to move, please link the new issue to this one.
