### ISSUE TITLE
Refactoring: remove some code from base.vim

### ISSUE THREAD

**Issue by tinmarino** [vimwiki/vimwiki#958]
### Tasks:

* [ ] Create link.vim
* [ ] Create heading.vim
* [ ] Create buffer.vim
* [ ] Merge all explore functions

### Brief:
Too much independent code is in `base.vim`
I advocate an architecture drawing in this github/wiki

**Comment by tinmarino** [comment]
## Example of functions

- exported : `goto_index` 
- used by other file : `vimwiki#base#find_files` used by `vimwiki#tags#update_tags` (So they are not so hight level)
- only using an other autoload : `vimwiki_get_known_syntaxes` using only vars
- are really central: `resolve_link` , `update_listing_in_buffer` and should stay here
- are a closed group not necessaryly usd by all users : `RemoveHeaderLevel`
- are repeated in markdown_base.vim, path.vim

## Proposal

Also I propose to move `style.css` and `default.tpl` in some `res` folder` to be separated from vim files.

I will propose a 3 level architecture (even if all in the same autoload/vimwiki directory) like

Base > List > Vars

## Objectives:

1. Code readable
2. Lazy file loading without making file too small either
  - I mean one could make one function per file but at the end there will be more io
  - Just to hide what user may not use   until he uses it (Heading, Link, FileTrees, TableMovement, Hightlighting, User Interface and Messaging)

## Related issues

* Make settings wikilocal: #894   <-- this one leads the way of refactoring (as data structure lead your code) so priority
* Path Refraction: #478
* Update markdown syntax: #664
* Add a Hook system for many user specific issues (taged config), issue postponed to more stable times


# Please comment !

We are thousands of small devs. Even a small message from your smartphone to give me red or green signal. Be sure to downvote and shout if this may break your code: (e.g there is a lot to integrate in handling-path branch)
Also I have a question: better to make small commits no ? Some 10 lines commit better than 30 lines ?
@ranebrown @Nudin @brennen @hq6 @EinfachToll @thecliguy @guntari

**Comment by ranebrown** [comment]
I agree some restructuring would be good. It could end up being a big effort though. As for the commits, I don't think it is as important the number of lines in a commit but each commit should be a cohesive change of related code.

**Comment by Nudin** [comment]
Sorry for not answering in time. I'm always happy if we get the code cleaned up to allow more people to easier contribute. Your proposal seems sound and wouldn't break anything I have in development. There are two functions that we mention in the help page, that a therefore a lot of people might have used in mappings or similar:
- `vimwiki#base#linkify()`
- `vimwiki#base#resolve_link(link)`
If we move or remove them we might want to think about giving users a helping hand for updating their vimrc.

Also pinging @tbabej and @liskin from taskwiki to ask if it might affect them?

**Comment by tbabej** [comment]
Hey @Nudin, no objections from taskwiki end, we always strive to run on top of recent vimwiki master, if any of the refactoring ends up affecting them, we'll adapt :) but from what was discussed here, nothing should directly affect us on the first glance.

**Comment by tinmarino** [comment]
Hi @Nudin and @tbabej. Glab to have the green fire. He is my plan, I may span this issue over the month:

1/ Analyse (Timing, Dependencies)
2/ Draw architecture (File system and dynamic)
3/ Refactor
4/ Add some startup test: Some ftpugin functions as defined in table should not be loaded if filetype is not vimwiki

**Comment by tinmarino** [comment]
# StartupTime

## No file
```
007.411  000.454  000.454: sourcing /home/tourneboeuf/.vim/pack/bundle/opt/wiki/autoload/vimwiki/vars.vim
008.850  000.154  000.154: sourcing /home/tourneboeuf/.vim/pack/bundle/opt/wiki/autoload/vimwiki/u.vim
014.729  000.043  000.043: sourcing /home/tourneboeuf/.vim/pack/bundle/opt/wiki/autoload/vimwiki/markdown_base.vim
014.781  001.292  001.249: sourcing /home/tourneboeuf/.vim/pack/bundle/opt/wiki/autoload/vimwiki/base.vim
014.958  000.154  000.154: sourcing /home/tourneboeuf/.vim/pack/bundle/opt/wiki/autoload/vimwiki/path.vim
019.229  012.393  010.339: sourcing /home/tourneboeuf/.vim/pack/bundle/opt/wiki/plugin/vimwiki.vim
......
031.956  000.006  000.006: sourcing /home/tourneboeuf/.vim/pack/bundle/opt/wiki/plugin/vimwiki.vim   # My bad if loaded again ? Anyway no time consumed
```
__Conclusion:__ 10ms for plugin/vimwiki.vim, can be reduced to 3ms

## Vimwiki file (`vim non_existing.md --startuptime su20.txt`)

```
006.885  000.413  000.413: sourcing /home/tourneboeuf/.vim/pack/bundle/opt/wiki/autoload/vimwiki/vars.vim
008.202  000.142  000.142: sourcing /home/tourneboeuf/.vim/pack/bundle/opt/wiki/autoload/vimwiki/u.vim
013.869  000.065  000.065: sourcing /home/tourneboeuf/.vim/pack/bundle/opt/wiki/autoload/vimwiki/markdown_base.vim
013.917  001.228  001.163: sourcing /home/tourneboeuf/.vim/pack/bundle/opt/wiki/autoload/vimwiki/base.vim
014.079  000.142  000.142: sourcing /home/tourneboeuf/.vim/pack/bundle/opt/wiki/autoload/vimwiki/path.vim
018.205  011.844  009.919: sourcing /home/tourneboeuf/.vim/pack/bundle/opt/wiki/plugin/vimwiki.vim
...
031.870  000.006  000.006: sourcing /home/tourneboeuf/.vim/pack/bundle/opt/wiki/plugin/vimwiki.vim
....
087.709  000.811  000.811: sourcing /home/tourneboeuf/.vim/ftplugin/vimwiki.vim
088.692  000.300  000.300: sourcing /home/tourneboeuf/.vim/pack/bundle/opt/wiki/autoload/vimwiki/tags.vim
092.844  004.880  004.580: sourcing /home/tourneboeuf/.vim/pack/bundle/opt/wiki/ftplugin/vimwiki.vim
100.411  001.087  001.087: sourcing /home/tourneboeuf/.vim/pack/bundle/opt/wiki/syntax/vimwiki_markdown_custom.vim
100.835  000.142  000.142: sourcing /usr/local/share/vim/vim82/syntax/tex.vim
107.652  006.504  006.504: sourcing /usr/local/share/vim/vim82/syntax/tex.vim
110.242  002.255  002.255: sourcing /home/tourneboeuf/.vim/pack/bundle/opt/wiki/autoload/vimwiki/emoji.vim
116.883  023.279  013.291: sourcing /home/tourneboeuf/.vim/pack/bundle/opt/wiki/syntax/vimwiki.vim
```

__Concusion:__
* 15ms for syntax/vimwiki
* 5ms for syntax/tex
* 3ms for the useless emoji.vim I added => I will fix this soon
* 1ms for base.vim which is really fast in fact
* 0.5 ms for vars.vim that is OK too

**Comment by Nudin** [comment]
Are times of ~15ms relevant? Would rather focus on code understandability and flexibility.

**Comment by tinmarino** [comment]
@Nudin 15ms is what we have now. I wrote that as a reference

I may not reduce it but do not want to increase it.

**Comment by tinmarino** [comment]
Closing <= stagnant long term issue
